Repository azimuth-cloud/ansible-collection-azimuth-ops, pull requests merged in 2024-02, with the labels that each got.

#334 Access admin dashboards using ingress + basic auth
  .github/workflows/test-pr.yml
  playbooks/deploy.yml
  playbooks/generate_tests.yml
  roles/admin_dashboard_ingress/defaults/main.yml
  roles/admin_dashboard_ingress/tasks/main.yml
  roles/azimuth_caas_operator/defaults/main.yml
  roles/capi_cluster/defaults/main.yml
  roles/capi_cluster/tasks/main.yml
  roles/kube_prometheus_stack/defaults/main.yml
  roles/zenith/defaults/main.yml
Labels: enhancement, breaking

#340 Add HuggingFace LLM as default app
  roles/azimuth_capi_operator/defaults/main.yml
Labels: enhancement

#349 Allow HA deployment to proceed with only changes to addons
  roles/capi_cluster/tasks/main.yml
Labels: bug

#314 Switch to opentofu
  README.md
  galaxy.yml
Labels: enhancement

#391 Add support for seed node volume type
  roles/infra/defaults/main.yml
  roles/infra/templates/resources.tf.j2
Labels: enhancement
